require 'rails_helper'
require 'pry'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe WonkoVersionsController, type: :controller do
  # This should return the minimal set of attributes required to create a valid
  # WonkoVersion. As you add validations to WonkoVersion, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { Fabricate.attributes_for(:wv_minecraft_183) }

  let(:invalid_attributes) do
    {
      wonko_file: {},
      asdf: '',
      stuff: nil
    }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # WonkoVersionsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe 'GET #index' do
    it 'assigns all wonko_versions as @wonko_versions' do
      wonko_version = Fabricate(:wv_minecraft_183)
      get :index, wonko_file_id: wonko_version.wonko_file.to_param
      expect(assigns(:wonko_versions).to_a).to eq([wonko_version])
    end
  end

  describe 'GET #show' do
    it 'assigns the requested wonko_version as @wonko_version' do
      wonko_version = Fabricate(:wv_minecraft_183)
      get :show, wonko_file_id: wonko_version.wonko_file.to_param, id: wonko_version.to_param
      expect(assigns(:wonko_version)).to eq(wonko_version)
    end

    context 'with wur' do
      let(:wonko_file) { Fabricate(:wf_minecraft) }
      let(:user) { Fabricate(:user) }
      let(:wv_inofficial) { Fabricate(:wv_minecraft_183, user: user, wonko_file: wonko_file) }
      let(:wv_official) { Fabricate(:wv_minecraft_183, user: User.official_user, wonko_file: wonko_file) }
      before(:each) do
        # generate a few red herings
        Fabricate(:wv_minecraft_183, user: Fabricate(:user), wonko_file: wonko_file)
        Fabricate(:wv_minecraft_183, user: Fabricate(:user), wonko_file: wonko_file)
      end

      context 'enabled' do
        it 'and no official and no param gives list' do
          get :show, wonko_file_id: wonko_file.to_param, id: wv_inofficial.to_param, wur: :true
          expect(response).to render_template('wonko_versions/list_of_variants')
          expect(assigns(:wonko_versions).to_a).to eq(wonko_file.wonkoversions.to_a)
        end
        it 'and no official and no param but only one shows it' do
          version = Fabricate(:wv_minecraft_181, user: Fabricate(:user), wonko_file: wonko_file)
          get :show, wonko_file_id: wonko_file.to_param, id: version.to_param, wur: true
          expect(response).to render_template('wonko_versions/show')
          expect(assigns(:wonko_version)).to eq(version)
        end
        it 'and none at all gives 404' do
          get :show, wonko_file_id: wonko_file.to_param, id: '1.7.10'
          expect(response).to render_template('errors/404')
        end
        it 'and no official and param gives inofficial' do
          get :show, wonko_file_id: wonko_file.to_param, id: wv_inofficial.to_param, wur: :true, user: user.to_param
          expect(assigns(:wonko_version)).to eq(wv_inofficial)
          expect(assigns(:wonko_version).user).to eq(user)
          expect(response).to render_template('wonko_versions/show')
        end
        it 'and official and no param gives official' do
          get :show, wonko_file_id: wonko_file.to_param, id: wv_official.to_param, wur: true
          expect(assigns(:wonko_version)).to eq(wv_official)
          expect(assigns(:wonko_version).user).to eq(User.official_user)
          expect(response).to render_template('wonko_versions/show')
        end
        it 'and official and param gives inofficial' do
          get :show, wonko_file_id: wonko_file.to_param, id: wv_inofficial.to_param, wur: true, user: user.to_param
          expect(assigns(:wonko_version)).to eq(wv_inofficial)
          expect(assigns(:wonko_version).user).to eq(user)
          expect(response).to render_template('wonko_versions/show')
        end
      end
      context 'disabled' do
        it 'and no official gives error gives 404' do
          get :show, wonko_file_id: wonko_file.to_param, id: '1.7.10'
          expect(response).to render_template('errors/404')
        end
        it 'and no official but inofficial gives hint' do
          wonko_version = Fabricate(:wv_minecraft_181, user: user, wonko_file: wonko_file)
          get :show, wonko_file_id: wonko_file.to_param, id: wonko_version.to_param
          expect(response).to render_template('wonko_versions/list_of_variants')
          expect(assigns(:wonko_versions).to_a).to eq([wonko_version])
        end
        it 'and official gives official' do
          get :show, wonko_file_id: wonko_file.to_param, id: wv_official.to_param
          expect(assigns(:wonko_version)).to eq(wv_official)
          expect(response).to render_template('wonko_versions/show')
        end
      end
    end
  end

  describe 'GET #new' do
    login_user

    it 'assigns a new wonko_version as @wonko_version' do
      wonko_file = Fabricate(:wf_minecraft)
      get :new, wonko_file_id: wonko_file.to_param
      expect(assigns(:wonko_version)).to be_a_new(WonkoVersion)
    end
  end

  describe 'GET #edit' do
    login_official

    it 'assigns the requested wonko_version as @wonko_version' do
      wonko_version = Fabricate(:wv_minecraft_183)

      get :edit, wonko_file_id: wonko_version.wonko_file.to_param, id: wonko_version.to_param
      expect(assigns(:wonko_version)).to eq(wonko_version)
    end
  end

  describe 'POST #upload' do
    login_user

    it 'updates a version' do
      file = Fabricate(:wf_minecraft, uid: 'net.minecraft.asdf.asdf')
      version = Fabricate(:wv_minecraft_183, wonko_file: file, time: 0, user: testing_user)
      expect do
        post :upload, file: Rack::Test::UploadedFile.new('spec/1.8.3.json', 'application/json')
      end.to change { file.reload.wonkoversions.count }.by(0)
      expect(version.reload.time).not_to eq(0)
    end
    it 'creates a new version' do
      file = Fabricate(:wf_minecraft, uid: 'net.minecraft.asdf.asdf')
      expect do
        post :upload, file: Rack::Test::UploadedFile.new('spec/1.8.3.json', 'application/json')
      end.to change { file.reload.wonkoversions.count }.by(1)
    end
  end

  describe 'POST #create' do
    let(:wonko_file) { Fabricate(:wf_minecraft) }
    login_user

    context 'with valid params' do
      it 'creates a new WonkoVersion' do
        expect do
          post :create, wonko_file_id: wonko_file.to_param,
                        wonko_version: Fabricate.attributes_for(:wv_minecraft_183)
        end.to change { wonko_file.reload.wonkoversions.count }.by(1)
      end

      it 'assigns a newly created wonko_version as @wonko_version' do
        post :create, wonko_file_id: wonko_file.to_param,
                      wonko_version: Fabricate.attributes_for(:wv_minecraft_183)
        expect(assigns(:wonko_version)).to be_a(WonkoVersion)
        expect(assigns(:wonko_version)).to be_persisted
      end

      it 'redirects to the created wonko_version' do
        attributes = Fabricate.attributes_for(:wv_minecraft_183)
        post :create, wonko_file_id: wonko_file.to_param,
                      wonko_version: attributes
        expect(response).to redirect_to(wonko_file_wonko_version_path(wonko_file, attributes[:version],
                                                                      user: testing_user.username))
      end
    end

    context 'with invalid params' do
      it 'assigns a newly created but unsaved wonko_version as @wonko_version' do
        post :create, wonko_file_id: Fabricate(:wf_minecraft).to_param, wonko_version: invalid_attributes
        expect(assigns(:wonko_version)).to be_a_new(WonkoVersion)
      end

      it 're-renders the \'new\' template' do
        post :create, wonko_file_id: Fabricate(:wf_minecraft).to_param, wonko_version: invalid_attributes
        expect(response).to render_template('new')
      end
    end
  end

  describe 'GET #copy' do
    let(:wonko_file) { Fabricate(:wf_minecraft) }
    login_user

    context 'with same user' do
      let(:wonko_version) { Fabricate(:wv_minecraft_181, wonko_file: wonko_file, user: testing_user) }

      it 'doesn\'t change and redirects to own' do
        version = wonko_version
        expect do
          get :copy, wonko_file_id: wonko_file.to_param, id: version.to_param, user: testing_user.username,
                     wur: true
        end.to change { wonko_file.reload.wonkoversions.count }.by(0)
        expect(response).to redirect_to(wonko_file_wonko_version_path(wonko_file, wonko_version,
                                                                      user: testing_user.username))
      end
    end

    context 'with different user' do
      let(:other_user) { Fabricate(:user) }
      let(:wonko_version) { Fabricate(:wv_minecraft_181, wonko_file: wonko_file, user: other_user) }

      it 'creates a new WonkoVersion' do
        version = wonko_version
        expect do
          get :copy, wonko_file_id: wonko_file.to_param, id: version.to_param, user: wonko_version.user.username,
                     wur: true
        end.to change { wonko_file.reload.wonkoversions.count }.by(1)
      end

      it 'assigns a newly created wonko version as @wonko_version' do
        get :copy, wonko_file_id: wonko_file.to_param, id: wonko_version.to_param, user: wonko_version.user.username,
                   wur: true
        expect(assigns(:wonko_version)).to be_a(WonkoVersion)
        expect(assigns(:wonko_version)).to be_persisted
      end

      it 'redirects to the created wonko version' do
        get :copy, wonko_file_id: wonko_file.to_param, id: wonko_version.to_param, user: wonko_version.user.username,
                   wur: true
        expect(response).to redirect_to(wonko_file_wonko_version_path(wonko_file, wonko_version.to_param,
                                                                      user: testing_user.username))
      end
    end
  end

  describe 'PUT #update' do
    login_official

    context 'with valid params' do
      let(:new_attributes) do
        {
          time: 1_111_111_111,
          type: 'stable'
        }
      end

      it 'updates the requested wonko_version' do
        wonko_version = Fabricate(:wv_minecraft_181)

        put :update, wonko_file_id: wonko_version.wonko_file.to_param, id: wonko_version.to_param,
                     wonko_version: new_attributes
        wonko_version.reload
        expect(wonko_version.type).to eq 'stable'
      end

      it 'assigns the requested wonko_version as @wonko_version' do
        wonko_version = Fabricate(:wv_minecraft_181)

        put :update, wonko_file_id: wonko_version.wonko_file.to_param, id: wonko_version.to_param,
                     wonko_version: new_attributes
        expect(assigns(:wonko_version)).to eq(wonko_version)
      end

      it 'redirects to the wonko_version' do
        wonko_version = Fabricate(:wv_minecraft_181)

        put :update, wonko_file_id: wonko_version.wonko_file.to_param, id: wonko_version.to_param,
                     wonko_version: new_attributes
        expect(response).to redirect_to(wonko_file_wonko_version_path wonko_version.wonko_file, wonko_version,
                                                                      user: testing_user)
      end
    end

    context 'with invalid params' do
      it 'assigns the wonko_version as @wonko_version' do
        wonko_version = Fabricate(:wv_minecraft_181)

        put :update, wonko_file_id: wonko_version.wonko_file.to_param, id: wonko_version.to_param,
                     wonko_version: invalid_attributes
        expect(assigns(:wonko_version)).to eq(wonko_version)
      end

      it 're-renders the \'edit\' template' do
        wonko_version = Fabricate(:wv_minecraft_181)

        put :update, wonko_file_id: wonko_version.wonko_file.to_param, id: wonko_version.to_param,
                     wonko_version: invalid_attributes
        expect(response).to render_template('edit')
      end
    end
  end

  describe 'DELETE #destroy' do
    login_official

    it 'destroys the requested wonko_version' do
      wonko_version = Fabricate(:wv_minecraft_181)
      file = wonko_version.wonko_file

      expect do
        delete :destroy, wonko_file_id: file.to_param, id: wonko_version.to_param
      end.to change { file.reload.wonkoversions.count }.by(-1)
    end

    it 'redirects to the wonko_versions list' do
      wonko_version = Fabricate(:wv_minecraft_183)

      delete :destroy, wonko_file_id: wonko_version.wonko_file.to_param, id: wonko_version.to_param
      expect(response).to redirect_to(wonko_file_wonko_versions_url(wonko_version.wonko_file))
    end
  end
end
